{% set name = "wagtail-review" %}
{% set version = "0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wagtail-review-{{ version }}.tar.gz
  sha256: 989638729af00abff0308c8f9410bc607fd64e5574da8dd907c064a25e13aab0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - swapper >=1.1,<1.2

test:
  imports:
    - wagtail_review
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wagtail/wagtail-review
  summary: Review workflow for Wagtail
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
